name: Pull Request Validation
on:
  push:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Python script
        run: python3 check_required_files.py
      
      - name: Log to CloudWatch
        if: success()
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          EPOCH_MS=$(($(date +%s) * 1000))
          LOG_MESSAGE='{"workflow":"${{ github.workflow }}","commit":"${{ github.sha }}","actor":"${{ github.actor }}","timestamp":"'${TIMESTAMP}'"}'
          
          aws logs create-log-stream \
            --log-group-name "${{ secrets.LOG_GROUP_PROD }}" \
            --log-stream-name "${TIMESTAMP}" || true
          
          aws logs put-log-events \
            --log-group-name "${{ secrets.LOG_GROUP_PROD }}" \
            --log-stream-name "${TIMESTAMP}" \
            --log-events "timestamp=${EPOCH_MS},message=${LOG_MESSAGE}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}