name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Python script
        run: python3 check_required_files.py
      
      - name: Log to CloudWatch
        if: success()
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          aws logs create-log-stream \
            --log-group-name "${{ secrets.LOG_GROUP_BETA }}" \
            --log-stream-name $TIMESTAMP
          aws logs put-log-events \
            --log-group-name "${{ secrets.LOG_GROUP_BETA }}" \
            --log-stream-name $TIMESTAMP \
            --log-events timestamp=$(($(date +%s) * 1000)),message="{\"workflow\":\"${{ github.workflow }}\",\"commit\":\"${{ github.sha }}\",\"actor\":\"${{ github.actor }}\",\"timestamp\":\"$TIMESTAMP\"}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
